apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodclassifier-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodclassifier
  template:
    metadata:
      labels:
        app: foodclassifier
    spec:
      containers:
      - name: cv-app
        image: gcr.io/<your-project-id>/foodclassifier
        ports:
        - containerPort: 8501